#Se especifica que se va a utilizar la version 2.1 de docker compose file
#Referencia a https://docs.docker.com/compose/compose-file/compose-file-v2/
version: '2.1'

#Se indica que se crean servicios
services:
#Se nombra a los servicios
#b1, b2 y b3 son routers de borde de SA. 
  b1:
    #Se utiliza para indicar donde esta el Dockerfile que se quiere utilizar para crear el contenedor.
    build: ./bgp/.
     #Aqui se hace que el directorio actual se mapee directamente con los directorios listados.
    #De este modo, cualquier cambio en el directorio local en el host, se hara de inmediato en el contenedor.
    volumes:
      - ./volumes/bgp/b1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/b1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/bgp/b1/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    #Crea una imagen llamada "bgp" en el directorio especificado en build
    image: bgp:20180426
    #Indica que se van a requerir privelegios de administrador
    privileged: true
    #Se mapean los siguientes puertos de la forma HOST:CONTAINER
    ports:
      #admin
      - 10101:2601
      #ospf ipv6
      - 10103:2606
      #bgp
      - 10104:2605
    #Se asignan las direcciones ipv4 e ipv6 al container 
    networks:
      oam:
        ipv6_address: 2001::5
      nr1b1:
        ipv6_address: 2001:aaaa:aaaa::5
  b2:
    build: ./bgp/.
    volumes:
      - ./volumes/bgp/b2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/b2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/bgp/b2/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: bgp:20180426
    privileged: true
    ports:
      #admin
      - 10201:2601
      #ospf ipv6
      - 10203:2606
      #bgp
      - 10204:2605
    networks:
      oam:
        ipv6_address: 2001::6
      nr2b2:
        ipv6_address: 2001:bbbb:bbbb::6
 
  b3:
    #Se utiliza para indicar donde esta el Dockerfile que se quiere utilizar para crear el contenedor.
    build: ./bgp/.
    #Aqui se hace que el directorio actual se mapee directamente con los directorios listados.
    #De este modo, cualquier cambio en el directorio local en el host, se hara de inmediato en el contenedor.
    volumes:
      - ./volumes/bgp/b3/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/b3/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/bgp/b3/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    #Crea una imagen llamada "bgp" en el directorio especificado en build
    image: bgp:20180426
    #Indica que se van a requerir privelegios de administrador
    privileged: true
    #Se mapean los siguientes puertos de la forma HOST:CONTAINER
    ports:
      #admin
      - 10301:2601
      #ospf ipv6
      - 10303:2606
      #bgp
      - 10304:2605
    #Se asignan las direcciones ipv4 e ipv6 al container 
    networks:
      b1_b2:
        ipv6_address: 2001::5
      b1_b3:
        
      nr1b1:
        ipv6_address: 2001:aaaa:aaaa::5
  #r1 y r2 no hablan el protocolo BGP debido a que no son routers de borde de SA.
  r1:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10111:2601
      #ospf ipv6
      - 10113:2606
    networks:
      nr1b1:
        ipv6_address: 2001:aaaa:aaaa::10
      nr1:
        ipv6_address: 2001:aaaa:1111::10
          
  r2:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10211:2601
      #ospf ipv6
      - 10213:2606
    networks:
      nr2b2:
        ipv6_address: 2001:bbbb:bbbb::10
      nr2:
        ipv6_address: 2001:bbbb:2222::10

#Se definen los enlaces y las redes a las cuales pertenecen
networks:
  oam:
    #Se usa bridge como driver para poder conectar los dockers en el host.
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001::/64
  nr1b1:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:aaaa::/64
  nr2b2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb::/64
  nr1:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaaa:1111::/64
  nr2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:2222::/64
