#Se especifica que se va a utilizar la version 2.1 de docker compose file
#Referencia a https://docs.docker.com/compose/compose-file/compose-file-v2/
version: '2.1'

#Se indica que se crean servicios
services:

#Se nombra a los servicios
  r1:

  #Se utiliza para indicar donde esta el Dockerfile que se quiere utilizar para crear el contenedor.
  #Al poner “.” automaticamente considerara el Dockerfile existene en directorio actual.
    build: .

    #Aqui se hace que el directorio actual se mapee directamente con los directorios listados.
    #De este modo, cualquier cambio en el directorio local en el host, se hara de inmediato en el contenedor.
    volumes:
      - ./volumes/quagga/r1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r1/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro

    #Crea una imagen llamada "ospf" en el directorio especificado en build
    image: ospf:20180419

    #Indica que se van a requerir privelegios de administrador
    privileged: true

    #Se mapean los siguientes puertos de la forma HOST:CONTAINER
    ports:
      #admin
      - 20011:2601
      #ospf
      - 20012:2604
      #ospf ipv6
      - 20013:2606

    #Se asignan las direcciones ipv4 e ipv6 al container
    networks:
      r1_r2:
        ipv6_address: 2001::28
      r3_r1:
        ipv6_address: 2001:aa31::11
      r5_r1:
        ipv6_address: 2001:aa51::11
      r7_r1:
        ipv6_address: 2001:aa71::11


  ##Se aplican los mismos comentarios sobre r2
  r2:
    build: .
    volumes:
      - ./volumes/quagga/r2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r2/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 20021:2601
      #ospf
      - 20022:2604
      #ospf ipv6
      - 20023:2606
    networks:
      r1_r2:
        ipv6_address: 2001::12
      r2_r4:
        ipv6_address: 2001:bb24::2
      r2_r6:
        ipv6_address: 2001:bb26::2
      r2_r8:
        ipv6_address: 2001:bb28::2


  ##Se aplican los mismos comentarios sobre r3
  r3:
    build: .
    volumes:
      - ./volumes/quagga/r3/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r3/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r3/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 20031:2601
      #ospf
      - 20032:2604
      #ospf ipv6
      - 20033:2606
    networks:
      r3_r1:
        ipv6_address: 2001:aa31::3
      r3lo:
        ipv6_address: 2001:aaa3::3


  ##Se aplican los mismos comentarios sobre r4
  r4:
    build: .
    volumes:
      - ./volumes/quagga/r4/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r4/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r4/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 20041:2601
      #ospf
      - 20042:2604
      #ospf ipv6
      - 20043:2606
    networks:
      r2_r4:
        ipv6_address: 2001:bb24::4
      r4lo:
        ipv6_address: 2001:bbb4::4

  ##Se aplican los mismos comentarios sobre r5
  r5:
    build: .
    volumes:
      - ./volumes/quagga/r5/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r5/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r5/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 20051:2601
      #ospf
      - 20052:2604
      #ospf ipv6
      - 20053:2606
    networks:
      r5_r1:
        ipv6_address: 2001:aa51::5
      r5_r7:
        ipv6_address: 2001:aa57::5
      h11_r5:
        ipv6_address: 2001:a115::5

  ##Se aplican los mismos comentarios sobre r6
  r6:
    build: .
    volumes:
      - ./volumes/quagga/r6/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r6/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r6/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 20061:2601
      #ospf
      - 20062:2604
      #ospf ipv6
      - 20063:2606
    networks:
      r2_r6:
        ipv6_address: 2001:bb26::6
      r6_r8:
        ipv6_address: 2001:bb68::6
      r6_h12:
        ipv6_address: 2001:b612::6

  ##Se aplican los mismos comentarios sobre r7
  r7:
    build: .
    volumes:
      - ./volumes/quagga/r7/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r7/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r7/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 20071:2601
      #ospf
      - 20072:2604
      #ospf ipv6
      - 20073:2606
    networks:
      r7_r1:
        ipv6_address: 2001:aa71::7
      r5_r7:
        ipv6_address: 2001:aa57::7
      h13_r7:
        ipv6_address: 2001:a137::7

  ##Se aplican los mismos comentarios sobre r8
  r8:
    build: .
    volumes:
      - ./volumes/quagga/r8/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r8/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r8/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 20081:2601
      #ospf
      - 20082:2604
      #ospf ipv6
      - 20083:2606
    networks:
      r2_r8:
        ipv6_address: 2001:bb28::8
      r6_r8:
        ipv6_address: 2001:bb68::8
      r8_h14:
        ipv6_address: 2001:b814::8


  ##Se aplican los mismos comentarios sobre r8
  h11:
      build: .
      volumes:
        - ./volumes/quagga/h11/zebra.conf:/etc/quagga/zebra.conf:ro
        - ./volumes/quagga/h11/ospfd.conf:/etc/quagga/ospfd.conf:ro
        - ./volumes/quagga/h11/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
        - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      image: ospf:20180419
      privileged: true
      ports:
        #admin
        - 20111:2601
        #ospf
        - 20112:2604
        #ospf ipv6
        - 20113:2606
      networks:
        h11_r5:
          ipv6_address: 2001:a115::11

  ##Se aplican los mismos comentarios sobre r8
  h12:
      build: .
      volumes:
        - ./volumes/quagga/h12/zebra.conf:/etc/quagga/zebra.conf:ro
        - ./volumes/quagga/h12/ospfd.conf:/etc/quagga/ospfd.conf:ro
        - ./volumes/quagga/h12/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
        - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      image: ospf:20180419
      privileged: true
      ports:
        #admin
        - 20121:2601
        #ospf
        - 20122:2604
        #ospf ipv6
        - 20123:2606
      networks:
          r6_h12:
            ipv6_address: 2001:b612::12

  ##Se aplican los mismos comentarios sobre r8
  h13:
      build: .
      volumes:
        - ./volumes/quagga/h13/zebra.conf:/etc/quagga/zebra.conf:ro
        - ./volumes/quagga/h13/ospfd.conf:/etc/quagga/ospfd.conf:ro
        - ./volumes/quagga/h13/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
        - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      image: ospf:20180419
      privileged: true
      ports:
        #admin
        - 20131:2601
        #ospf
        - 20132:2604
        #ospf ipv6
        - 20133:2606
      networks:
        h13_r7:
          ipv6_address: 2001:a137::13



  ##Se aplican los mismos comentarios sobre r8
  h14:
      build: .
      volumes:
        - ./volumes/quagga/h14/zebra.conf:/etc/quagga/zebra.conf:ro
        - ./volumes/quagga/h14/ospfd.conf:/etc/quagga/ospfd.conf:ro
        - ./volumes/quagga/h14/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
        - ./volumes/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      image: ospf:20180419
      privileged: true
      ports:
        #admin
        - 20141:2601
        #ospf
        - 20142:2604
        #ospf ipv6
        - 20143:2606
      networks:
          r8_h14:
            ipv6_address: 2001:b814::14










#Se definen los enlaces y las redes a las cuales pertenecen
networks:

  r1_r2:
    #Se usa bridge como driver para poder conectar los dockers en el host.
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001::/64

  r3_r1:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aa31::/64

  r5_r1:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aa51::/64

  r7_r1:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aa71::/64

  r2_r4:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bb24::/64

  r2_r6:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bb26::/64

  r2_r8:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bb28::/64

  r3lo:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aaa3::/64

  r4lo:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbb4::/64

  r5_r7:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:aa57::/64

  h11_r5:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a115::/64

  r6_r8:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bb68::/64

  r6_h12:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:b612::/64

  h13_r7:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:a137::/64

  r8_h14:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:b814::/64
